# Generated by Django 4.1.1 on 2022-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='this space is availaqble for a small fee', max_length=500),
            preserve_default=False,
        ),
    ]
