# Generated by Django 4.1.1 on 2022-10-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(default=1),
        ),
    ]
